name: Docker CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build --no-cache -t pvnode .
          docker save -o pvnode.tar pvnode

      - name: Upload image to artifact
        uses: actions/upload-artifact@v2
        with:
          name: pvnode.tar
          path: pvnode.tar
